name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSmall, ReleaseSafe, ReleaseFast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          cache-key: ${{ matrix.optimize }}
      - run: zig build test -Doptimize=${{ matrix.optimize }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - run: zig build install
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - run: zig fmt --check .
